[package]
name = "tsunami"
version = "0.9.0"

description = "Toolkit for running short-lived jobs on EC2 spot instances"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/tsunami"
homepage = "https://github.com/jonhoo/tsunami"
repository = "https://github.com/jonhoo/tsunami.git"

keywords = ["ec2", "aws", "spot-instances", "distributed", "benchmark"]
categories = []

license = "MIT/Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "jonhoo/tsunami" }
maintenance = { status = "passively-maintained" }

[features]
debug = ["slog/max_level_trace", "slog/release_max_level_debug"]

[dependencies]
itertools = "0.8"
rusoto_core = "0.40"
rusoto_ec2 = "0.40"
ssh2 = "0.3.2"
failure = "0.1.1"
rand = "0.7"
tempfile = "3.0.0"
rayon = "1.0.0"
slog-term = "2"
#slog = "2"
slog = { version = "2", features = ["max_level_trace"] }

[profile.release]
debug = true
